name: Build and Test sailfishos for dumpling
on:
  repository_dispatch:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - run: |
        sudo apt update
        git clone https://github.com/sailfishos/mic
        #git clone https://github.com/jfding/mic
        
        wget https://github.com/gmicroul/dumpling-sfos-ci/raw/refs/heads/main/VERSION
        pwd
        ls -ltrh
        cd mic
        cp VERSION mic/
        ls mic/ -ltrh
        ls -ltrh
        pwd
        make
        sudo make install
        cd ..
        source dumpling.env
        bash run-mic.sh
        ls -ltrh
         
      
    - name: Upload a Build Artifact
      #id: compile
      uses: actions/upload-artifact@v4.3.0
      with:
        name: 'dumpling sailfishos images'
        path: './*.zip*'
