name: Build sailfishos for enchilada-new
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_example:
        description: "oneplus"
        required: true
        default: "enchilada"

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker container
        run: |
          sudo docker pull coderus/sailfishos-platform-sdk-base:latest
          sudo docker run --privileged --name sailfish-sdk -d coderus/sailfishos-platform-sdk-base:latest tail -f /dev/null

      - name: Copy files into Docker container
        run: |
          sudo docker cp . sailfish-sdk:/workspace

      - name: Run build inside Docker
        run: |
          sudo docker exec sailfish-sdk sh -c "cd /workspace && source ./enchilada.env && sudo bash ./run-mic2.sh"

      - name: List files in Docker container
        run: |
          sudo docker exec sailfish-sdk ls -R /workspace  # List files recursively to verify output location

      - name: Archive artifacts
        run: |
          # Check the output directory inside Docker and then copy it
          sudo docker exec sailfish-sdk ls -ltrh /workspace/sfe-enchilada-5.0.0.67/
          # Adjust the path based on the output of the previous step
          sudo mkdir -p /home/runner/work/enchilada-sfos-ci/enchilada-sfos-ci/artifacts/
          sudo docker cp sailfish-sdk:/workspace/sfe-enchilada-5.0.0.67/sailfishos-5.0.0.67-20250503-enchilada-SLOT_a.zip /home/runner/work/enchilada-sfos-ci/enchilada-sfos-ci/artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-enchilada-sailfishos
          path: /home/runner/work/enchilada-sfos-ci/enchilada-sfos-ci/artifacts/*.zip

      - name: Cleanup
        run: |
          sudo docker stop sailfish-sdk
          sudo docker rm sailfish-sdk
          
      - name: Upload image to Release
        uses: ncipollo/release-action@main
        with:
          tag: SailfishOS_for_enchilada
          artifacts:  /home/runner/work/enchilada-sfos-ci/enchilada-sfos-ci/artifacts/*.zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            SailfishOS_for_enchilada
