name: Build sailfishos for dumpling
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_example:
        description: "oneplus"
        required: true
        default: "dumpling"

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker container
        run: |
          docker pull coderus/sailfishos-platform-sdk-base:latest
          docker run --privileged --name sailfish-sdk -d coderus/sailfishos-platform-sdk-base:latest tail -f /dev/null
          #docker run --name sailfish-sdk -d coderus/sailfishos-platform-sdk-base:latest tail -f /dev/null

      - name: Copy files into Docker container
        run: |
          docker cp . sailfish-sdk:/workspace
          
      - name: Run build inside Docker
        run: |
          docker exec sailfish-sdk sh -c "cd /workspace && source ./dumpling.env && sudo bash ./run-mic.sh"

      - name: Archive artifacts
        run: |
          #docker exec -it sailfish-sdk ls /workspace/sfe-*/
          docker cp sailfish-sdk:/workspace/sfe-dumpling-3.4.0.24/sailfishos-3.4.0.24-20241119-dumpling.zip /home/runner/work/dumpling-sfos-ci/dumpling-sfos-ci/artifacts/
          #ls -ltrh ./artifacts/
          pwd
          ls -ltrh
          zip_path=$(readlink -f /home/runner/work/dumpling-sfos-ci/dumpling-sfos-ci/artifacts/)
          echo "Zip path: $zip_path"
          echo "::set-output name=zip_path::$zip_path"
        id: get_zip_path
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-dumpling-sailfishos
          #path: ./artifacts/*.zip
          path: ${{ steps.get_zip_path.outputs.zip_path }}/*.zip

      - name: Cleanup
        run: |
          docker stop sailfish-sdk
          docker rm sailfish-sdk
